version: "2"

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    image: aliops
    container_name: aliops-app
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.yml:/opt/app/config.yml

  auth:
    image: nginx:alpine
    container_name: aliops-auth
    links:
      - app:app
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
      - ./user.db:/etc/nginx/conf.d/user.db
    ports:
      - 8080:8080
    restart: always