domains:
  - dev.siss.io:
      # for change dns record
      domain: siss.io
      # for nginx
      nginx:
        ssh_user: username
        hosts:
          - 128.0.255.2
          - 128.0.255.3
      config_file: /etc/nginx/conf.d/dev.siss.io.conf
      slbs:
        - lb-wz9d9j05rzlyok300fcf4
        - lb-wz9obyqmiidllwulomjxh
      backend_port: 8080
      backends:
        - 128.0.255.6:81
        - 128.0.255.7:81
      ips:
        - 120.77.199.116
        - 47.107.24.104

  - www.unknowname.win:
      # for change dns record
      domain: unknowname.win
      # for nginx
      config_file: /etc/nginx/conf.d/www.unknowname.win.conf
      slbs:
        - lb-wz9d9j05rzlyok300fcf4 #Jumpserver
        - lb-wz9obyqmiidllwulomjxh #test
      backend_port: 80
      backends:
        - 128.0.255.27:80
        - 128.0.255.28:80
      ips:
        - 47.107.24.104
        - 47.107.17.249
        - 120.77.111.55
# Global NGINX.if domains section no nginx present,use here
nginx:
  ssh_user: username
  hosts:
    - 128.0.255.12
    - 128.0.255.13

api:
  aeskey: keyid
  aeskey_secret: key-secret
  region: cn-shenzhen

dns_api:
  aeskey: aaa
  aeskey_secret: bbb
  region: cn-shenzhen