domains:
  - display: ops.sissyun.com.cn_test
    domain: sissyun.com.cn
    # 与之相关的，即修改这个，会同时修改它的relatives,需要后端服务器的ID+端口相一致，用于一组机器承载多个负载均衡
    relatives:
      - finance-internal
    slb:
      # if not present,Use default backends
      backend_virtual_name: graylog #bank-consumer
      type: clb #clb/nlb
      ids:
      - lb-wz9obyqmiidllwulomjxh
      # - lb-wz9obeo6c187qydidoehe
    ips:
    # ips要和正式解析对应，否则页面不显示，用于DNS修改
    - 39.108.27.240

  - display: finance-internal
    # if it is true,don't display on page
    invisible: true
    slb:
      type: nlb
      backend_virtual_name: test
      ids:
      - nlb-oon7cfhgpay4l6quu1

  - display: test.unknowname.cn_18912
    domain: unknowname.cn
    ips:
      - 2.2.2.2
    # 如果有配置项，将会在nginx页面显示
    nginx:
      ssh_user: username
      hosts:
      - 128.0.255.2
      - 128.0.255.3
      # in NGINX config file.the upstream server's port
      # exits the backend_port,the domain will display on /nginx URL
      backend_port: 8080,80 # 多端口用逗号分隔
      config_file: /etc/nginx/conf.d/dev.siss.io.conf

# Global NGINX.if domains section no nginx present,use here
nginx:
  ssh_user: username
  hosts:
    - 128.0.255.12
    - 128.0.255.13

slb_api:
  key: key
  secret: secret
  region: cn-shenzhen

dns_api:
  key: key
  secret: secret
  region: cn-shenzhen

es:
  addr: 128.0.255.10
  port: 9200
  index: indexName