domains:
  - dev.siss.io:
      # for change dns record
      domain: siss.io
      # for nginx
      nginx:
        ssh_user: username
        hosts:
          - 128.0.255.2
          - 128.0.255.3
      # in NGINX config file.the upstream server's port
      # exits the backend_port,the domain will display on /nginx URL
      backend_port: 8080
      config_file: /etc/nginx/conf.d/dev.siss.io.conf
      slbs:
        # No set, will no display on /slb url
        # - lb-wz9d9j05rzlyok300fcf4
        # - lb-wz9obyqmiidllwulomjxh
      ips:
        # No set,  will no display on /dns url
        - 120.77.199.116
        # - 47.107.24.104

  - www.unknowname.win:
      # for change dns record
      domain: unknowname.win
      # for nginx
      config_file: /etc/nginx/conf.d/www.unknowname.win.conf
      backend_port: 80
      slbs:
        - lb-wz9d9j05rzlyok300fcf4 #Jumpserver
        - lb-wz9obyqmiidllwulomjxh #test
      ips:
        - 47.107.24.104
        - 47.107.17.249
        - 120.77.111.55
# Global NGINX.if domains section no nginx present,use here
nginx:
  ssh_user: username
  hosts:
    - 128.0.255.12
    - 128.0.255.13

api:
  aeskey: LTAI4FnP7Ljoghn33kGyEE8X
  aeskey_secret: iFeMvPwVzxceBTjgtPIX7f9JxlhrJA
  region: cn-shenzhen

dns_api:
  aeskey: ""
  aeskey_secret: ""
  region: cn-shenzhen